theme = "github_dark_dimmed"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
# Move line up
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "goto_line_start"]
# Move line down
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after", "goto_line_start"]
# Duplicate line up
"C-A-up" = ["extend_line","yank","open_above","normal_mode","replace_with_yanked"]
# Duplicate line down
"C-A-down" = ["extend_line","yank","move_line_down","open_above","normal_mode","replace_with_yanked"]
